### ISSUE TITLE
The module "./lib/module.mjs" was not found on the file system

### ISSUE THREAD

**Issue by theoparis** [sveyret/intl-ts#11]
I was building a frontend project with ESM and it gave this upon building the frontend with esbuild:

```
   node_modules/intl-ts/package.json:31:12: note: The module "./lib/module.mjs" was not found on the file system
```

**Comment by sveyret** [comment]
Hi @creepinson 
Indeed, the file is not present in the package. Sorry for that and thank you for warning me.
As a workaround, until I make a correction, you can manually take the `src/module.mjs` file that you can find on the repository instead.

**Comment by sveyret** [comment]
Should be corrected in new version.
